### PR TITLE
Update astro.svg

### PR DESCRIPTION
**Pull request by lorenzolewis**
Astro's brand identity has been updated and has slowly been refreshing any visuals. I've swapped the light mode image that is on their press page: https://astro.build/press/

I don't see any way to add a dark mode icon and also don't see one implemented for any other logos so only I've only included the light mode icon for this one.

### CODE REVIEW

**Comment by saadeghi** [comment]
Thanks!

**Comment by lorenzolewis** [comment]
Quick follow-up: Would you be open to a PR that renders the relevant dark or light logo based on the Tailwind Dark Mode?

**Comment by saadeghi** [comment]
Yes, that would be great! Thanks!  
The problem is, only some logos need dark version. Currently we're loading the image path from a JS object so the JS object needs to include a second image path for dark mode, then in the markup if that object property exists and if theme is dark, then it should show the other image.

**Comment by lorenzolewis** [comment]
Cool, just put in PR https://github.com/saadeghi/daisyui/pull/3190. Currently have it in a draft and would like your feedback on the approach first then will proceed.

**Pull request merged**
